// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiO6uCp1jFozkowDbMQNvy9CY-flfhRHk',
    appId: '1:215268959923:web:b240a7d69c42a72884b2c6',
    messagingSenderId: '215268959923',
    projectId: 'astro-ai-433ed',
    authDomain: 'astro-ai-433ed.firebaseapp.com',
    storageBucket: 'astro-ai-433ed.firebasestorage.app',
    measurementId: 'G-4FNV93JDCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ij7LyD2PpVdoc20YOgNvLQsbu5IGmOE',
    appId: '1:215268959923:android:f22764144827528084b2c6',
    messagingSenderId: '215268959923',
    projectId: 'astro-ai-433ed',
    storageBucket: 'astro-ai-433ed.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVHrco-JHr7z_ckXQWveXUUJ0krkRY-M',
    appId: '1:215268959923:ios:62ff9832f5a781a984b2c6',
    messagingSenderId: '215268959923',
    projectId: 'astro-ai-433ed',
    storageBucket: 'astro-ai-433ed.firebasestorage.app',
    iosClientId: '215268959923-mn2v4bjb631ui0tpm24hm7o4hkkil33d.apps.googleusercontent.com',
    iosBundleId: 'com.example.astroAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWVHrco-JHr7z_ckXQWveXUUJ0krkRY-M',
    appId: '1:215268959923:ios:62ff9832f5a781a984b2c6',
    messagingSenderId: '215268959923',
    projectId: 'astro-ai-433ed',
    storageBucket: 'astro-ai-433ed.firebasestorage.app',
    iosClientId: '215268959923-mn2v4bjb631ui0tpm24hm7o4hkkil33d.apps.googleusercontent.com',
    iosBundleId: 'com.example.astroAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiO6uCp1jFozkowDbMQNvy9CY-flfhRHk',
    appId: '1:215268959923:web:19d449473797c30a84b2c6',
    messagingSenderId: '215268959923',
    projectId: 'astro-ai-433ed',
    authDomain: 'astro-ai-433ed.firebaseapp.com',
    storageBucket: 'astro-ai-433ed.firebasestorage.app',
    measurementId: 'G-QBSWY2Q9EN',
  );
}
